import {planToSVG as plan90} from '../90/plan.js';
import {planToSVG as plan125} from '../125/plan.js';
import layout90 from '../90/layout.js';
import {facts as facts125} from '../125/plan-source.js';
import fs from 'node:fs';
const base='site/assets/';
for(const level of ['ground','upper'])fs.writeFileSync(base+`combstruct-90-${level==='ground'?'parter':'poddasze'}.svg`,plan90(level));
fs.writeFileSync(base+'combstruct-125-plan.svg',plan125());
fs.writeFileSync('lib/construction/qa/facts.json',JSON.stringify({90:layout90.facts,125:facts125},null,2));
console.log(JSON.stringify({90:layout90.facts,125:facts125}));
