export const topics = [
 {id:'deska',group:'Elementy i zasady',title:'Deska grzebieniowa',lead:'Jeden powtarzalny element tworzy podłogę, ściany, strop i dach.',text:'Deskę wycinamy z płyty OSB, MFP lub sklejki. Wpusty sięgają do połowy jej wysokości. Dwie deski złożone powierzchniami tworzą parę, a krótsze warianty zachowują ten sam skok modułu.',rule:'24 cm wysokości. 18 mm grubości jednej deski.',scene:'beam'},
 {id:'uciaglanie',group:'Elementy i zasady',title:'Para desek i uciąglanie',lead:'Przedłużamy żebro, dokładając kolejne deski w dwóch warstwach.',text:'Łączenia warstw mijają się: przy końcu deski w jednej warstwie biegnie pełny odcinek drugiej. W tym przykładzie rozsunięcie wzdłuż belki wynosi dwa moduły. Zakończenie jednej warstwy jest krótsze o 24 cm.',rule:'Styki obu warstw nie wypadają w tym samym miejscu.',scene:'continuity',spread:true},
 {id:'podloga-strop',group:'Elementy i zasady',title:'Podłoga i strop',lead:'Żebra równoległe do krótszej krawędzi płyty mają wpusty do góry.',text:'To stała zasada układania. Na modelu wyróżniliśmy tę rodzinę żeber turkusem. Żebra biegnące prostopadle mają wpusty w przeciwną stronę, dzięki czemu obie rodziny składają się na krzyż.',rule:'Krótszy kierunek nośny — wpusty do góry.',scene:'slab',arrows:true,spread:true},
 {id:'sciany-zewnetrzne',group:'Elementy i zasady',title:'Ściany zewnętrzne',lead:'Pionowe żebra mają wpusty skierowane na zewnątrz domu.',text:'Turkusowe piony pokazują właściwą orientację. Poziome żebra łączą się z nimi od przeciwnej strony. Ściana zaczyna się od poziomu podstawy konstrukcji, a jej zakończenia tworzą połączenie z podłogą.',rule:'Piony: wpusty na zewnątrz. Linia żeber pozostaje ciągła.',scene:'wall',arrows:true,spread:true},
 {id:'dach',group:'Elementy i zasady',title:'Dach',lead:'Także w dachu krótszy kierunek płyty ma wpusty do góry.',text:'Na połaci „do góry” oznacza stronę pokrycia dachowego. Wyróżnione żebra biegną równolegle do krótszej krawędzi połaci. Druga rodzina zamyka siatkę od przeciwnej strony.',rule:'Ta sama zasada co w stropie, obrócona razem z połacią.',scene:'roof',arrows:true,spread:true},
 {id:'deski-laczeniowe',group:'Elementy i zasady',title:'Zakończenia i deski łączeniowe',lead:'Te same deski, przygotowane do konkretnego miejsca w połączeniu.',text:'Zakończenie skracamy o wysokość deski: 24 cm. Deski łączeniowe mają lokalne wybranie odsłaniające pół wpustu na kolejne żebro. Wybierz wariant, aby obejrzeć sam kształt.',rule:'Wybranie odsłania wpust. Nie przesuwamy przez nie osi żeber.',scene:'connectors',variants:true},
 {id:'krzyzowanie',group:'Połączenia',title:'Żebra na krzyż',lead:'Dwie prostopadłe pary wsuwają się w siebie przez wpusty.',text:'Każda rodzina oddaje połowę wysokości w miejscu skrzyżowania. Po złożeniu obie mieszczą się w jednej warstwie konstrukcyjnej o głębokości 24 cm. Rozsuń elementy, aby zobaczyć obie strony wpustu.',rule:'Wpust do góry spotyka wpust do dołu.',scene:'cross',spread:true},
 {id:'podloga-sciana',group:'Połączenia',title:'Podłoga — ściana zewnętrzna',lead:'Dłuższa część zakończenia przylega do boku pełnego żebra.',text:'Krótsza opiera się o żebro, a dłuższa schodzi obok niego do poziomu podstawy konstrukcji. Para ściany i para podłogi pozostają w tej samej płaszczyźnie.',rule:'Pełna deska i zakończenie uzupełniają się na 24 cm.',scene:'joint',joint:'edge-floor',spread:true},
 {id:'taras',group:'Połączenia',title:'Podłoga — ściana — taras',lead:'Podłoga może biec dalej, poza obrys domu.',text:'Jedna warstwa przechodzi przez węzeł na taras. Druga przyjmuje pion ściany. Narożne wybranie 18 × 102 mm wraz z istniejącym półwpustem odsłania miejsce na poprzeczne żebro.',rule:'Ciągłość tarasu i miejsce na wszystkie trzy kierunki żeber.',scene:'joint',joint:'terrace',spread:true,crossing:true},
 {id:'podloga-wewnetrzna',group:'Połączenia',title:'Podłoga — ściana wewnętrzna',lead:'Ściana wewnętrzna wchodzi w plaster podłogi na tej samej zasadzie.',text:'Pion zaczyna się przy podstawie konstrukcji. Krótsze zakończenie opiera się na pełnym żebrze, a dłuższe przylega do jego boku. Odsunięte wybranie w pełnej krawędzi pozostawia miejsce na drugie żebro podłogi.',rule:'Wspólna linia żeber, bez dodatkowej deski pod ścianą.',scene:'joint',joint:'interior-floor',spread:true,crossing:true},
 {id:'polaczenie-scian',group:'Połączenia',title:'Ściana wewnętrzna — zewnętrzna',lead:'Poziome żebra obu ścian spotykają się w jednej płaszczyźnie.',text:'Zakończenia składają się naprzemiennie. Wybranie w zębatej krawędzi, odsunięte od końca deski, odsłania wpust na pion ściany zewnętrznej. Końcówka pozostaje zachowana.',rule:'Trzeci element wchodzi w odsłonięty wpust.',scene:'joint',joint:'wall-wall',spread:true,crossing:true},
 {id:'naroznik',group:'Połączenia',title:'Narożnik ścian zewnętrznych',lead:'Dwie ściany zamykają obrys w narożniku.',text:'Poziome pary spotykają się naprzemiennie pełną deską i zakończeniem. Każda ściana zachowuje swój kierunek: wpusty jej pionowych żeber otwierają się na zewnątrz budynku.',rule:'Dwie ściany, wspólny poziom par desek.',scene:'corner',spread:true},
 {id:'sciany-wewnetrzne',group:'Połączenia',title:'Połączenie ścian wewnętrznych',lead:'Przegroda poprzeczna dochodzi do ciągłej ściany.',text:'Jedna warstwa przechodzi przez skrzyżowanie, druga przyjmuje zakończenie przegrody. Lokalne wybranie pozostawia miejsce na pion, bez odsuwania którejkolwiek pary poza linię żeber.',rule:'Zakończenie wchodzi w ciągłą parę desek.',scene:'joint',joint:'partition-t',spread:true,crossing:true},
 {id:'strop-sciana',group:'Połączenia',title:'Strop — ściana zewnętrzna',lead:'Zakończenie stropu wykorzystuje pełne żebro ściany.',text:'Krótsza część opiera się na żebrze, dłuższa przylega do niego z boku. Deska łączeniowa odsłania wpust na poziomy rząd ściany. Pion może kontynuować swój bieg ponad stropem.',rule:'Strop nie przerywa linii konstrukcji ściany.',scene:'joint',joint:'ceiling-wall',spread:true,crossing:true},
 {id:'strop-wewnetrzna',group:'Połączenia',title:'Strop — ściana wewnętrzna',lead:'Pion dochodzi do stropu w tej samej linii co żebro podłogi.',text:'Pełna deska stropu przechodzi przez węzeł. Zakończenia obu przegród uzupełniają się, a wybranie pozostawia miejsce na poprzeczne żebro stropu.',rule:'Ta sama geometria zakończeń na dole i na górze ściany.',scene:'joint',joint:'ceiling-partition',spread:true,crossing:true},
 {id:'dach-sciana',group:'Połączenia',title:'Dach — ściana',lead:'Żebro połaci trafia w linię pionowego żebra ściany.',text:'Zbliżenie pokazuje rzeczywisty fragment modelu domu przy okapie. Żebro dachowe biegnie dalej poza ścianę, tworząc okap. Kąt połaci wyznacza kształt styku przy podparciu.',rule:'Połać i ściana spotykają się na tej samej linii żebra.',scene:'roof-wall'},
 {id:'kalenica',group:'Połączenia',title:'Połączenie połaci w kalenicy',lead:'Dwie połacie zamykają dach dopasowanymi zakończeniami.',text:'W tym modelu połacie mają nachylenie 35°. Końce żeber są docięte do płaszczyzny kalenicy, tak aby obie bryły stykały się bez nakładania. To połączenie kątowe, zależne od geometrii dachu.',rule:'Kąt i zakończenie wynikają z projektu dachu.',scene:'ridge'}
];

export const variants=[
 {id:'standard',name:'Zwykła',trim:null,cut:null,description:'Pełna deska z wpustami i półwpustami na końcach.'},
 {id:'ending',name:'Zakończeniowa',trim:'left',cut:null,description:'Jedna warstwa pary krótsza o 24 cm — wysokość deski.'},
 {id:'corner-slotted',name:'Narożna · 102 mm',cut:{edge:'slotted',offset:0},description:'18 × 102 mm nowego wybrania oraz 18 mm istniejącego półwpustu.'},
 {id:'corner-plain',name:'Narożna · 120 mm',cut:{edge:'plain',offset:0},description:'Wybranie 18 × 120 mm przy pełnej krawędzi końca deski.'},
 {id:'inset-slotted',name:'Odsunięta · zęby',cut:{edge:'slotted',offset:.12},description:'Wybranie przy zębach, odsunięte od końca; zachowana końcówka.'},
 {id:'inset-plain',name:'Odsunięta · pełna krawędź',cut:{edge:'plain',offset:.12},description:'Wybranie przy pełnej krawędzi, odsunięte od końca deski.'}
];
