import source from './layout.js';
import {normalizeWalls} from '../panels.js';
const layout=structuredClone(source),a=layout.axes;
layout.source={path:'lib/construction/125/layout.js'};
layout.terrace={x0:-6.25,x1:1.25,z0:5,z1:7.5};
layout.planWalls=normalizeWalls(layout.partitions,{x0:-6.25,x1:6.25,z0:-5,z1:5}).map(w=>({...w,uOrigin:0}));
for(const r of layout.rooms)r.area=(r.x1-r.x0)*(r.z1-r.z0);
const polygon=[[a.utilityX+.12,-4.76],[a.wetSpine-.12,-4.76],[a.wetSpine-.12,4.76],[-6.01,4.76],[-6.01,a.utilityZ+.12],[a.utilityX+.12,a.utilityZ+.12]];
layout.living={name:'Salon + jadalnia + kuchnia',polygon,area:Math.abs(polygon.reduce((s,p,i)=>s+p[0]*polygon[(i+1)%polygon.length][1]-polygon[(i+1)%polygon.length][0]*p[1],0))/2};
export const facts={width:12.5,depth:10,footprintArea:125,terraceArea:18.75,roomsArea:layout.rooms.reduce((s,r)=>s+r.area,0)+layout.living.area,bedrooms:3,bathrooms:1,separateWC:true,floors:1,interiorHeight:9*(2.5/6)-.48};
export default layout;
